### ISSUE TITLE
Typo in arXiv paper.

### ISSUE THREAD

**Issue by RunpeiDong** [deepseek-ai/DreamCraft3D#1]
Hi authors, 

Thanks for your interesting work. I found that the ICLR camera-ready running title "Published as a conference paper in ICLR 2024" is not removed😂. This is a typo since ICLR 2024 papers are still under review and I think you should fix it to avoid misleading.

Regards

**Comment by MrTornado24** [comment]
Hello, thank you so much for identifying this significant mistake. We take it very seriously and will fix it today. Our apologies for any confusion caused.
