### ISSUE TITLE
No directory named "load"

### ISSUE THREAD

**Issue by pavpanda** [deepseek-ai/DreamCraft3D#14]
I can't seem to find the load directory and thus can't start the first step of training. Could that be added to the repo? Thanks so much! This work is great.

**Comment by Iliceth** [comment]
@pavpanda I copied that directory from the threestudio repo and that got me further.

**Comment by pavpanda** [comment]
Got it, thanks — how long did the whole training procedure take you? And what are your GPU specs?

**Comment by Iliceth** [comment]
Unfortunately, I got stuck with errors after that, see issue #16 , so can't tell yet, sorry.
