### ISSUE TITLE
Getting FileNotFoundError 

### ISSUE THREAD

**Issue by mitdave95** [deepseek-ai/DreamCraft3D#19]
When running the first process, `python launch.py --config configs/dreamcraft3d-coarse-nerf.yaml --train system.prompt_processor.prompt="$prompt" data.image_path="$image_path"`

getting this error
`FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/e89966d7424b11d100b42f7e2bfde05e.pt for model DeepFloyd/IF-I-XL-v1.0 and prompt [a brightly colored mushroom growing on a log] not found.
`

**Comment by Subin-Kim46** [comment]
I got the same error

**Comment by MrTornado24** [comment]
Hello, the issue you likely resulted from having local_files_only=True set when loading diffusion guidance. I've now removed this setting. It should function properly now.

**Comment by FayizUmar** [comment]
FileNotFoundError: outputs/dreamcraft3d-coarse-nerf/a_brightly_colored_mushroom_growing_on_a_log@20241107-122137/ckpts/last.ckpt
