### ISSUE TITLE
论文公式询问

### ISSUE THREAD

**Issue by a574824551** [deepseek-ai/DreamCraft3D#2]
![1698306181248](https://github.com/deepseek-ai/DreamCraft3D/assets/29809521/f09fc87b-913c-4216-906d-e3496feb5c35)
你好，读论文的时候看到这块，感觉这个式子是不是写错了？
另外想问下dreambooth优化纹理处，是将初始的参考图加上其他视角的生成图，迭代优化stable diffusion模型嘛~

**Comment by TiankaiHang** [comment]
Also, Equation (4): covariance $\text{conv} (\cdot)$ --> $\text{cov} (\cdot)$

**Comment by MrTornado24** [comment]
@a574824551 是的，这个公式的第二项少了$\omega，感谢提醒～对于第二个问题，是的，我们将参考图也输入进去来优化模型。

**Comment by MrTornado24** [comment]
@TiankaiHang Thank you for pointing that out; we'll correct this typo.
