### ISSUE TITLE
About the result of mushroom

### ISSUE THREAD

**Issue by Amuseum-WHR** [deepseek-ai/DreamCraft3D#23]
Hello, I run your code on the mushroom case (on A100). However, my result is quite different with the provided demo video. I wonder whether your mushroom-demo was run with the yaml file you provide in this repo. The main difference is that my "log" is not a cylinder, but either a land or a board. This is a result from neus (Stage 1) 
<img width="797" alt="image" src="https://github.com/deepseek-ai/DreamCraft3D/assets/75399920/72225c88-8645-4bab-9486-b96f35e29764">

By the way, I can often observe the pure color (e.g. the pure green in the log) in Stage 1 (and may remain even after Stage III), as you may see in the following image. Have you ever met with similar problems?
<img width="407" alt="image" src="https://github.com/deepseek-ai/DreamCraft3D/assets/75399920/bc6c6fc2-857d-48be-9fee-e4df7dd30882">

**Comment by Amuseum-WHR** [comment]
And I met with another problem. In Stage II, the backview of my DMTet result is not as smooth as yours, maybe it's because of some hyperparameters?

**Comment by Time-Lord12th** [comment]
Hello, I'm also trying to do some tests. Are you using the faster version? It takes 40mins to generate a 3d model from a single image?

**Comment by Amuseum-WHR** [comment]
hello, I am using the current version on an A100, and it takes me about 2~3 hours with the given config files.

**Comment by Amuseum-WHR** [comment]
> Hello, I'm also trying to do some tests. Are you using the faster version? It takes 40mins to generate a 3d model from a single image?

hello, I am using the current version on an A100, and it takes me about 2~3 hours with the given config files.
