### ISSUE TITLE
hyperparameters questions

### ISSUE THREAD

**Issue by flyingdoubleG** [deepseek-ai/DreamCraft3D#24]
Thanks for the great work, I tried to generate a corgi in the paper using the official code, but it seems that the hyperparameters in the official code may be a little different from the paper, can you give some advice on improving the result?
The picture I use:
![corgi](https://github.com/deepseek-ai/DreamCraft3D/assets/53119724/c4e5b303-7706-473b-8a4a-8bd182307302)
The prompt I use:
"A DSLR photo of a corgi wearing a beret and holding a baguette, standing up on two hind legs"
other hyperparameters are not changed.
The model I generate:
https://github.com/deepseek-ai/DreamCraft3D/assets/53119724/fc34a686-1c3b-4e9b-be6b-8f4f7c8ceb27

**Comment by MrTornado24** [comment]
Hi I also noticed that stable-zero123 doesn't work well for some cases. You may change to zero123-xl which we used in the paper.
