### ISSUE TITLE
Clarification in Algorithm 1

### ISSUE THREAD

**Issue by jfozard** [deepseek-ai/DreamCraft3D#5]
Hi - wonderful results. Could you please give more details of what r_{t'}(x) is in Algorithm 1. If it is the denoised version of x_{t'} , which diffusion model and which method (DDIM etc.) is used to generate r_{t'}(x)?

**Comment by MrTornado24** [comment]
Yes, it is the denoised version of x_{t'}, and we use SD 2.1 with DDIM.
