### ISSUE TITLE
No module named 'tinycudann'

### ISSUE THREAD

**Issue by Yhc-777** [deepseek-ai/DreamCraft3D#58]
Sorry to bother you in your busy schedule. I wanna ask how to install 'tinycudann',  I cannot install it successfully, please help me... Thanks a lot!!!

**Comment by fantasy-fish** [comment]
I have the same problem. Is there any solution here?

**Comment by Yhc-777** [comment]
> I have the same problem. Is there any solution here?

Not yet... Still debugging...

**Comment by breakerh** [comment]
You can build tinycudann from git.
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
