### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by Gitterman69** [deepseek-ai/DreamCraft3D#7]
when eta?! ;)

**Comment by CycloneRing** [comment]
**Coming Soon™**

**Comment by termene7** [comment]
Will we be able to provide ourselves the image?

**Comment by alekolo7** [comment]
yes

**Comment by pccross** [comment]
Will code be available before end of the year?  Trying to determine if I can use this for upcoming project.

**Comment by soloice** [comment]
check it again, guys
