### ISSUE TITLE
GPU requirements

### ISSUE THREAD

**Issue by violag** [deepseek-ai/DreamCraft3D#8]
Hi! 

Thank you for the amazing work!

Can you share more information on the compute requirements. How many GPUs did you use for the Geometry Sculpting phase and also for the Texture Boosting phase?

What was the memory size of the GPU that was required?

Thank you!

**Comment by MrTornado24** [comment]
We employed 8 units of 40G A100 for all stages of the process. However, the number of GPUs required is flexible, ranging from 1 to 8. For optimal performance, we recommend a memory size of at least 24G.

**Comment by maocaixia** [comment]
When we run "python launch.py --config configs/dreamcraft3d-coarse-neus.yaml --train system.prompt_processor.prompt="$prompt" data.image_path="$image_path" system.weights="$ckpt"
", there is an error "out of memory", the gpu is 4090 with 24G.

Any Suggestion? Thanks! @MrTornado24

**Comment by maocaixia** [comment]
Would we use multiple gpus to infer the model?

**Comment by CHDTevior** [comment]
> Would we use multiple gpus to infer the model?

we also have the same problem.
